### PR TITLE
* Update: Added manpages

### PR DESCRIPTION
**Pull request by hpersh**
Signed-off-by: Howard Persh <Howard_Persh@dell.com>

### CODE REVIEW

**Comment by jeff-yin** [comment]
@hpersh the opx-cps repo just took in a sync from other members of the dev team. Please resolve the merge conflict, thanks.

**Comment by hpersh** [comment]
@amybuck   Please suggest an improvement for 6 above.

**Comment by jeff-yin** [comment]
@hpersh I think @amybuck is referring to man/man1/cps_get_oid.py.1 line 31 -- change "namely" to "such as" instead.

**Comment by jeff-yin** [comment]
@hpersh can you push the small changes to resolve the above conflicts?

**Pull request closed without merging**
